CREATE TABLE t101_sz_hjy_sxd_profile (
    data_bsn_dt DATE NOT NULL COMMENT '数据业务日期',
    etl_dt DATE NOT NULL COMMENT '数据跑批日期',
    cst_id VARCHAR(200) NOT NULL COMMENT '客户编号',
    cst_nm VARCHAR(500) NOT NULL COMMENT '客户名称',
    fd_dt VARCHAR(50) COMMENT '成立时间',
    lgl_rprs_nm VARCHAR(200) COMMENT '法定代表人',
    act_cntlr_nm VARCHAR(200) COMMENT '实控人姓名',
    rgst_cpamt VARCHAR(50) COMMENT '注册资本',
    arcptl_cpamt VARCHAR(50) COMMENT '实收资本',
    credit_code VARCHAR(200) COMMENT '统一社会信用代码',
    CPCT_TPCD VARCHAR(50) COMMENT '企业类型',
    entp_sz_cd VARCHAR(50) COMMENT '企业规模',
    dtl_adr TEXT COMMENT '注册地址',
    org_oprt_scop_dsc TEXT COMMENT '经营范围',
    entp_bliy VARCHAR(500) COMMENT '所属行业',
    tech_tag VARCHAR(1000) COMMENT '企业科技资质类型',
    tech_flow VARCHAR(50) COMMENT '我行“技术流”评价结果',
    kc_score VARCHAR(50) COMMENT '我行“科创分”评价结果',
    ENTP_PTNT_NUM VARCHAR(50) COMMENT '企业专利数量',
    ENTPPRCTNEWTPPTNT_NUM VARCHAR(50) COMMENT '企业实用新型专利数',
    ENTP_IVT_PTNT_NUM VARCHAR(50) COMMENT '企业发明专利数',
    CLST5YRINNRSWCOPR_NUM VARCHAR(50) COMMENT '企业软件著作权数量',
    if_loan VARCHAR(50) COMMENT '是否我行贷款客户',
    product_name VARCHAR(50) COMMENT '最新贷款品种',
    loan_amount VARCHAR(100) COMMENT '贷款金额',
    loan_term VARCHAR(50) COMMENT '贷款期限',
    loan_balance VARCHAR(100) COMMENT '贷款当前余额',
    dep_bal VARCHAR(100) COMMENT '对公存款余额',
    dep_bal_dt VARCHAR(50) COMMENT '对公存款余额日期',
    dep_aadbal VARCHAR(100) COMMENT '对公存款年日均余额',
    acc_start_dt VARCHAR(50) COMMENT '开立账户时间',
    acc_type VARCHAR(50) COMMENT '对公账户类型（基本/一般）',
    isug_pnum VARCHAR(50) COMMENT '代发人数',
    avg_12_isug_amt VARCHAR(100) COMMENT '月均代发工资',
    if_yuqi VARCHAR(50) COMMENT '近两年是/否存在贷款逾期记录',
    ltgtrltd_ind VARCHAR(50) COMMENT '是/否存在司法纠纷',
    if_rad_alarm VARCHAR(50) COMMENT '是/否存在RAD红色预警风险信号',
    byzd1 VARCHAR(1000) COMMENT '备用字段1',
    byzd2 VARCHAR(1000) COMMENT '备用字段2',
    byzd3 VARCHAR(1000) COMMENT '备用字段3',
    byzd4 VARCHAR(1000) COMMENT '备用字段4',
    byzd5 VARCHAR(1000) COMMENT '备用字段5',
    byzd6 VARCHAR(1000) COMMENT '备用字段6',
    byzd7 VARCHAR(1000) COMMENT '备用字段7',
    byzd8 VARCHAR(1000) COMMENT '备用字段8',
    byzd9 VARCHAR(1000) COMMENT '备用字段9',
    byzd10 VARCHAR(1000) COMMENT '备用字段10'
) COMMENT='善新贷材料生成结果表';